spring.application.name=save-sync
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
spring.datasource.url=jdbc:h2:file:./savedata
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
